# Generated by Django 4.0.3 on 2022-03-23 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='title')),
                ('author', models.CharField(default='', max_length=100, verbose_name='author')),
                ('content', models.TextField(default='', verbose_name='content')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('up_votes', models.IntegerField(default=0, verbose_name='Upvotes')),
                ('down_votes', models.IntegerField(default=0, verbose_name='Downvotes')),
            ],
        ),
    ]
